[addresses]
  mock_dapp = '0xc60e02bda64de1d17e65d7227b985ce6856f04fe8402d1914c2c558f7c7d4216'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.xcall]
    local = '../xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'mock_dapp'
  published-at = '0xc60e02bda64de1d17e65d7227b985ce6856f04fe8402d1914c2c558f7c7d4216'
