[addresses]
  mock_dapp = '0xf592a8cb9dd276591ef7bcc55c550faeb70db9d2afa0e11be7ea1b39f25fa8fb'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.xcall]
    local = '../xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'mock_dapp'
  published-at = '0xf592a8cb9dd276591ef7bcc55c550faeb70db9d2afa0e11be7ea1b39f25fa8fb'
