[addresses]
  mock_dapp = '0xa428ba49777e18f424a509cfcc935744dc806560bb98c3f9c54449f1d6459c5b'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.xcall]
    local = '../xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'mock_dapp'
  published-at = '0xa428ba49777e18f424a509cfcc935744dc806560bb98c3f9c54449f1d6459c5b'
