[addresses]
  xcall = '0x9d5537b32615593cb0b5aaa49ef06bd67f2bd8de0ab35d3c6aaaebc67b87e005'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.sui_rlp]
    local = '../libs/sui_rlp'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.alpha'
  name = 'xcall'
  published-at = '0x9d5537b32615593cb0b5aaa49ef06bd67f2bd8de0ab35d3c6aaaebc67b87e005'
