[addresses]
  xcall = '0x693a60a5098b346acb773e37bff767fa90c85645ca9dba5d63741cf2bea848eb'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.sui_rlp]
    local = '../libs/sui_rlp'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.alpha'
  name = 'xcall'
  published-at = '0x3c99bd5253288dc42535374c68f2bc01cbeff2a9674a3a7feeffb0af8fc50f96'
