[addresses]
  xcall = '0x2a815e1bb7e88902ae74b95d7a98a5b04d55a7cb282fcf104f9ff2c0465f6976'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.sui_rlp]
    local = '../libs/sui_rlp'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.alpha'
  name = 'xcall'
  published-at = '0x3e3424f015ae28e9c223ce5828e70746d4174024e087b42576cb6ea837ee9cd7'
