[addresses]
  xcall = '0x343e0315e35f3159f81c457dcba45e9e6bae6003d486924b7b33238e674addf7'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.sui_rlp]
    local = '../libs/sui_rlp'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.alpha'
  name = 'xcall'
  published-at = '0x343e0315e35f3159f81c457dcba45e9e6bae6003d486924b7b33238e674addf7'
