name: Build and Upload xcall-multi Contracts

on:
  push:
    branches:
      - "main"

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Javascore
        working-directory: contracts/javascore
        run: |
          ./gradlew clean build 
          ./gradlew optimizedJar
          ./gradlew zipOutputOptimizedJars

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: javascore-contracts
          path: ./contracts/javascore/build/javascore-contracts.zip
          if-no-files-found: error
          