name: Compile and publish Cosmwasm contracts to the GitHub Package Registry
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - contracts/cosmwasm-vm/**
      - libraries/common/rust/**
jobs:
  Build:
    name: Build Cosmasm Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Compile WASM
        run: |
          bash ./scripts/optimize-cosmwasm.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cosmwasm-contracts
          path: artifacts

