name: CosmWasm contracts Codecov

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "contracts/cosmwasm-vm/**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: contracts/cosmwasm-vm

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
        
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --lcov --output-path lcov.info --package cw-xcall
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: rust
          fail_ci_if_error: true