name: Cosmwasm Contracts Test Deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - contracts/cosmwasm-vm/**
      - libraries/common/rust/**
      - .github/workflows/deploy-cosmwasm-contracts.yml
      - scripts/optimize-cosmwasm.sh
jobs:
  Build:
    name: Build & Deploy Cosmasm Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Start local Archway Blockchain
        run: |
          cp ./scripts/archway/docker_compose_archway.yaml .
          docker compose -f docker_compose_archway.yaml up -d

      - name: Compile WASM
        run: |
          sudo chmod -R 777 artifacts
          sudo chmod -R 777 scripts
          bash ./scripts/optimize-cosmwasm.sh

      - name: Deploy WASM
        run: |
          container=$(docker ps --format '{{.Names}}')
          rm -rf artifacts/archway/cw_common.wasm
          docker exec $container chmod +x /opt/deploy_cosmwasm.sh
          docker exec $container /opt/deploy_cosmwasm.sh
