name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build jar
        working-directory: contracts/javascore
        run: ./gradlew clean build
      - name: Publish package
        working-directory: contracts/javascore
        run: |
          # Temporary workaround - uncomment maven publish block
          sed -i 's/^\/\/ //' build.gradle
          ./gradlew xcall-lib:publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          STAGING_PROFILE_ID : ${{ secrets.STAGING_PROFILE_ID }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey : ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword : ${{ secrets.SIGNING_PASSWORD }}
