name: Pre-release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  build_javascore:
    name: Build Javascore Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Javascore Contracts
        working-directory: contracts/javascore
        run: |
          ./gradlew clean build
          ./gradlew optimizedJar
          ./gradlew zipOutputOptimizedJars
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: javascore-contracts
          path: ./contracts/javascore/build/javascore-contracts.zip
  build_wasm:
    name: Build Cosmwasm Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Compile WASM
        run: |
          # rustup component add rustfmt --toolchain 1.78.0-x86_64-unknown-linux-gnu
          # rustup component add clippy --toolchain 1.78.0-x86_64-unknown-linux-gnu     
          bash ./scripts/optimize-cosmwasm.sh
          cd artifacts/archway && zip -r ../../cosmwasm-contracts.zip . -j
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cosmwasm-contracts
          path: cosmwasm-contracts.zip
  build_solidity:
    name: Build Solidity Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: contracts/evm
        run: |
          git submodule update --init --recursive
          bash ./forge_build.sh
          cd artifacts && zip -r ../../../solidity-contracts.zip . -j
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solidity-contracts
          path: solidity-contracts.zip

  build_stellar:
    name: Build stellar Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
  
      - name: Install wasm32
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked stellar-cli --features opt
      - name: Compile WASM
        run: |
          bash ./scripts/optimize-stellar.sh
          cd artifacts/stellar && zip -r ../../stellar-contracts.zip . -j
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stellar-contracts
          path: stellar-contracts.zip

  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    needs:
      - build_javascore
      # - build_wasm
      - build_stellar
      - build_solidity
    steps:
      - name: Initialize variables
        id: vars
        run: |
          echo «::set-output name=date::$(date +'%Y-%m-%d')»
          echo «::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)»
      - name: Download Javascore Artifacts
        uses: actions/download-artifact@v4
        with:
          name: javascore-contracts
          path: javascore-contracts

      - name: Download Cosmwasm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cosmwasm-contracts
          path: cosmwasm-contracts

      - name: Download Solidity Artifacts
        uses: actions/download-artifact@v4
        with:
          name: solidity-contracts
          path: solidity-contracts

      - name: Download Stellar Artifacts
        uses: actions/download-artifact@v4
        with:
          name: stellar-contracts
          path: stellar-contracts

      - name: Unzip Javascore Artifacts
        run: unzip javascore-contracts/javascore-contracts.zip -d javascore-contracts && rm -rf javascore-contracts/javascore-contracts.zip

      - name: Unzip Cosmwasm Artifacts
        run: unzip cosmwasm-contracts/cosmwasm-contracts.zip -d cosmwasm-contracts && rm -rf cosmwasm-contracts/cosmwasm-contracts.zip

      - name: Unzip Cosmwasm Artifacts
        run: unzip solidity-contracts/solidity-contracts.zip -d solidity-contracts && rm -rf solidity-contracts/solidity-contracts.zip
     
      - name: Unzip Stellar Artifacts
        run: unzip stellar-contracts/stellar-contracts.zip -d stellar-contracts && rm -rf stellar-contracts/stellar-contracts.zip

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            javascore-contracts/*.jar
            solidity-contracts/*
            ./stellar-contracts/*
          output: check256sums.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          files: |
            ./javascore-contracts/*.jar
            ./solidity-contracts/*
            ./stellar-contracts/*
            check256sums.txt