name: Solidity contracts Codecov

env:
  FOUNDRY_PROFILE: ci

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "contracts/evm/**"
      - ".github/workflows/solidity-cov.yml"
  push:
    branches:
      - "**"

defaults:
  run:
    working-directory: contracts/evm

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build Contracts
        run: |
          forge remappings
          forge build

      - name: Generate code coverage
        run: |
          export PATH=$PATH:$HOME/.config/.foundry/bin
          forge coverage --report lcov
          sudo apt-get install lcov
          lcov --remove lcov.info 'test/*' 'script/*' 'library/*' '**/libraries/**' > lcov2.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov2.info
          flags: solidity
          fail_ci_if_error: true
