name: Build and Test Stellar contracts
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
    paths:
      - contracts/soroban/**
      - libraries/common/rust/**
      - .github/workflows/stellar-build-and-test.yml

defaults:
  run:
    working-directory: contracts/soroban
jobs:
  Build:
    name: Build Stellar Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.81.0
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install wasm32
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked soroban-cli

      - name: Build & Test Stellar Contracts
        working-directory: contracts/soroban
        run: |
            soroban contract build
