name: Deploy Contracts to uat node

on:
  push:
    branches:
      - "main"

jobs:
  deploy-contracts-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve the secret and decode it to a file
        working-directory: contracts/javascore
        env:
          UAT_KEYSTORE_B64: ${{ secrets.UAT_KEYSTORE_B64 }}
        run: |
          echo $UAT_KEYSTORE_B64 | base64 -d > key.json

      - name: Deploy all contracts on UAT environment
        working-directory: contracts/javascore
        env:
          UAT_KEYSTORE_PATH: ./key.json
          UAT_PASSWD: ${{ secrets.UAT_PASSWD }}
        run: |
          ./gradlew clean build 
          ./gradlew optimizedJar
          ./gradlew deployToUat -PdeploymentENV=uat -PkeystoreName=$UAT_KEYSTORE_PATH -PkeystorePass=$UAT_PASSWD